// <auto-generated />
using System;
using FeedLens.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedLens.Repositories.Migrations
{
    [DbContext(typeof(FeedLensDbContext))]
    [Migration("20260719193246_AddAlgorithmModeToUsers")]
    partial class AddAlgorithmModeToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeedLens.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "💻",
                            IsActive = true,
                            Name = "Technology",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Icon = "💰",
                            IsActive = true,
                            Name = "Finance",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Icon = "📚",
                            IsActive = true,
                            Name = "Education",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Icon = "🎬",
                            IsActive = true,
                            Name = "Entertainment",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Icon = "⚽",
                            IsActive = true,
                            Name = "Sports",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Icon = "🎵",
                            IsActive = true,
                            Name = "Music",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Icon = "🎮",
                            IsActive = true,
                            Name = "Gaming",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Icon = "✈️",
                            IsActive = true,
                            Name = "Travel",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Icon = "🍕",
                            IsActive = true,
                            Name = "Food",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Icon = "🏥",
                            IsActive = true,
                            Name = "Health",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Icon = "🔬",
                            IsActive = true,
                            Name = "Science",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Icon = "💼",
                            IsActive = true,
                            Name = "Business",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            Icon = "📰",
                            IsActive = true,
                            Name = "News",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            Icon = "😂",
                            IsActive = true,
                            Name = "Comedy",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            Icon = "💪",
                            IsActive = true,
                            Name = "Fitness",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            Icon = "🎨",
                            IsActive = true,
                            Name = "Art & Design",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            Icon = "📷",
                            IsActive = true,
                            Name = "Photography",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 18,
                            Icon = "👨‍💻",
                            IsActive = true,
                            Name = "Programming",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 19,
                            Icon = "🌟",
                            IsActive = true,
                            Name = "Lifestyle",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 20,
                            Icon = "📌",
                            IsActive = true,
                            Name = "Other",
                            SortOrder = 20
                        });
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgorithmMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailS3Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.WatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalSeconds")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<double>("WatchPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WatchedSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("WatchHistories");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.Like", b =>
                {
                    b.HasOne("FeedLens.Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FeedLens.Domain.Entities.Video", "Video")
                        .WithMany("Likes")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.Video", b =>
                {
                    b.HasOne("FeedLens.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FeedLens.Domain.Entities.User", "User")
                        .WithMany("Videos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.WatchHistory", b =>
                {
                    b.HasOne("FeedLens.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeedLens.Domain.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.User", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("FeedLens.Domain.Entities.Video", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
